steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/anipe-repo/anip-opportunity-identifier:latest', '-f', 'Dockerfile-opportunity.txt', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/anipe-repo/anip-opportunity-identifier:latest']

# Store images in Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/anipe-repo/anip-opportunity-identifier:latest'

options:
  logging: CLOUD_LOGGING_ONLY
